<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="78915" started-at="2020-07-22T06:32:21Z" finished-at="2020-07-22T06:33:40Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="78915" started-at="2020-07-22T06:32:21Z" finished-at="2020-07-22T06:33:40Z">
      <class name="failRun.HandleEnableElement">
        <test-method status="FAIL" signature="elementToClick()[pri:0, instance:failRun.HandleEnableElement@cb5822]" name="elementToClick" duration-ms="15601" started-at="2020-07-22T12:02:21Z" finished-at="2020-07-22T12:02:36Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [456] but found [123]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [456] but found [123]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at failRun.HandleEnableElement.elementToClick(HandleEnableElement.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- elementToClick -->
        <test-method status="PASS" signature="failSC(org.testng.ITestResult)[pri:0, instance:failRun.HandleEnableElement@cb5822]" name="failSC" is-config="true" duration-ms="2485" started-at="2020-07-22T12:02:36Z" finished-at="2020-07-22T12:02:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=elementToClick status=FAILURE method=HandleEnableElement.elementToClick()[pri:0, instance:failRun.HandleEnableElement@cb5822] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failSC -->
      </class> <!-- failRun.HandleEnableElement -->
      <class name="failRun.TestFB">
        <test-method status="FAIL" signature="openFB()[pri:0, instance:failRun.TestFB@4b9e13df]" name="openFB" duration-ms="46458" started-at="2020-07-22T12:02:39Z" finished-at="2020-07-22T12:03:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at failRun.TestFB.openFB(TestFB.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openFB -->
        <test-method status="PASS" signature="sc(org.testng.ITestResult)[pri:0, instance:failRun.TestFB@4b9e13df]" name="sc" is-config="true" duration-ms="14163" started-at="2020-07-22T12:03:25Z" finished-at="2020-07-22T12:03:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=openFB status=FAILURE method=TestFB.openFB()[pri:0, instance:failRun.TestFB@4b9e13df] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sc -->
      </class> <!-- failRun.TestFB -->
      <class name="failRun.Test4">
        <test-method status="PASS" signature="tesFour()[pri:0, instance:failRun.Test4@18be83e4]" name="tesFour" duration-ms="75" started-at="2020-07-22T12:02:21Z" finished-at="2020-07-22T12:02:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tesFour -->
      </class> <!-- failRun.Test4 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
